version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ride_sharing_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: